// Treść kursu. c() = pytanie z wyborem (a = indeks poprawnej opcji), t() = wpisz odpowiedź.
// Odpowiedzi wpisywane pisz w pełnej formie (has not); aplikacja rozumie też skróty (hasn't).
const c = (q, o, a, e) => ({ q, o, a, e });
const t = (q, a, e) => ({ q, t: a, e });

const GROUPS = [
  { id: "present", name: "Czasy teraźniejsze" },
  { id: "past", name: "Czasy przeszłe" },
  { id: "future", name: "Przyszłość" },
  { id: "constr", name: "Konstrukcje" },
  { id: "compare", name: "Porównania (najczęstsze pułapki)" },
];

const TOPICS = [
  // ───────────────────────── PRESENT ─────────────────────────
  {
    id: "present-simple", group: "present", name: "Present Simple",
    short: "nawyki, fakty, rozkłady jazdy",
    when: [
      "<b>Nawyki i rutyna</b> – co robisz regularnie: <i>I get up at 7.</i>",
      "<b>Fakty i prawdy ogólne</b>: <i>Water boils at 100°C.</i>",
      "<b>Rozkłady i harmonogramy</b> (pociągi, filmy, spotkania): <i>The train leaves at 8.</i>",
      "<b>Czasowniki stanu</b> (know, like, want, need, understand…) – prawie zawsze Simple, nie Continuous.",
    ],
    form: [
      ["Twierdzenie", "I/you/we/they <b>work</b> · he/she/it <b>works</b> (+s / +es)"],
      ["Przeczenie", "I/you/we/they <b>do not (don't) work</b> · he/she/it <b>does not (doesn't) work</b>"],
      ["Pytanie", "<b>Do</b> you work? · <b>Does</b> she work?"],
    ],
    sig: ["always", "usually", "often", "sometimes", "never", "every day", "on Mondays", "how often"],
    ex: [
      ["She works in a bank.", "Ona pracuje w banku."],
      ["I don't like coffee.", "Nie lubię kawy."],
      ["Does he speak French?", "Czy on mówi po francusku?"],
      ["The shop opens at 9.", "Sklep otwiera się o 9."],
    ],
    watch: [
      ["She work here.", "She works here.", "Po he/she/it dodajemy -s. To najczęstszy błąd Polaków."],
      ["Does she works?", "Does she work?", "Po does/did czasownik wraca do formy podstawowej – -s ma już „does”."],
      ["I am work every day.", "I work every day.", "„Am/is/are” + czasownik to Continuous, nie Simple."],
    ],
    tip: "Po polsku „nie mam” → <i>I don't have</i>. Nie tłumacz „nie” jako <i>no</i>. Przeczenie = <b>do/does + not</b>.",
    q: [
      c("She ___ coffee every morning.", ["drink", "drinks", "is drinking"], 1, "He/she/it + -s. Nawyk (every morning) → Present Simple."),
      c("___ you work on Saturdays?", ["Do", "Does", "Are"], 0, "You → Do. Pytanie w Present Simple zaczynamy od do/does."),
      t("He ___ (not/like) spicy food.", ["does not like"], "he + does not + czasownik w formie podstawowej: doesn't like."),
      c("The film ___ at 8 pm tonight.", ["start", "starts", "starting"], 1, "Harmonogram/rozkład → Present Simple; podmiot 3. osoby → starts."),
      c("Water ___ at 100°C.", ["boils", "is boiling", "boil"], 0, "Fakt naukowy → Present Simple."),
      t("Where ___ your brother live?", ["does"], "your brother = he → does. Po does czasownik bez -s: live."),
      c("My sister ___ a lot of TV.", ["don't watch", "doesn't watch", "isn't watch"], 1, "Sister = she → doesn't + watch (bez -es)."),
      t("I ___ (study) English three times a week.", ["study"], "I → bez końcówki -s. Regularność (three times a week)."),
    ],
  },
  {
    id: "present-continuous", group: "present", name: "Present Continuous",
    short: "dzieje się teraz, plany na najbliższą przyszłość",
    when: [
      "<b>Czynność w trakcie mówienia</b>: <i>Be quiet! I'm working.</i>",
      "<b>Sytuacja tymczasowa</b> („w tym okresie”): <i>I'm staying with friends this week.</i>",
      "<b>Ustalone plany na przyszłość</b> (umówione, zorganizowane): <i>I'm meeting Anna tomorrow.</i>",
      "<b>Irytujące nawyki</b> z <i>always</i>: <i>You're always losing your keys!</i>",
      "<b>Trwające zmiany</b>: <i>Prices are rising.</i>",
    ],
    form: [
      ["Twierdzenie", "I <b>am</b> / he,she,it <b>is</b> / you,we,they <b>are</b> + <b>working</b>"],
      ["Przeczenie", "I <b>am not</b> working · he <b>isn't</b> working · they <b>aren't</b> working"],
      ["Pytanie", "<b>Are</b> you working? · <b>Is</b> she working?"],
    ],
    sig: ["now", "at the moment", "right now", "currently", "today", "this week", "Look!", "Listen!"],
    ex: [
      ["It's raining. Take an umbrella.", "Pada. Weź parasol."],
      ["I'm reading a great book at the moment.", "Czytam teraz świetną książkę."],
      ["We're flying to Rome on Friday.", "W piątek lecimy do Rzymu."],
      ["Are you listening to me?", "Czy ty mnie słuchasz?"],
    ],
    watch: [
      ["I am knowing the answer.", "I know the answer.", "Czasowniki stanu (know, like, love, want, need, understand, believe) nie występują w Continuous."],
      ["I'm working here since May.", "I've been working here since May.", "„Od kiedy / od jak dawna” → Perfect, nie Present Continuous (jak po polsku „pracuję od maja”)."],
    ],
    tip: "Po polsku mówimy „pracuję” zarówno na „ogólnie pracuję” jak i „właśnie pracuję”. Po angielsku to dwa różne czasy: <i>I work</i> (ogólnie) vs <i>I'm working</i> (teraz).",
    q: [
      c("Be quiet! The baby ___.", ["sleeps", "is sleeping", "sleep"], 1, "Dzieje się teraz → Present Continuous."),
      c("I ___ my keys. Have you seen them?", ["look for", "am looking for", "looks for"], 1, "Szukanie w tej chwili → am looking for."),
      t("They ___ (not/watch) TV now.", ["are not watching"], "aren't watching – are + not + czasownik-ing."),
      c("I ___ what you mean.", ["understand", "am understanding", "understanding"], 0, "understand to czasownik stanu – nie używamy go w Continuous."),
      c("We ___ to Spain next week. We've bought the tickets.", ["go", "are going", "will going"], 1, "Ustalony plan z biletami → Present Continuous."),
      c("He ___ his phone at dinner! It's so annoying.", ["always checks", "is always checking", "has always checked"], 1, "always + Continuous = irytujący nawyk."),
      t("Look! It ___ (rain).", ["is raining"], "Look! = dzieje się teraz → is raining."),
      c("She ___ in London at the moment; she moved there in May.", ["lives", "is living", "live"], 1, "Sytuacja tymczasowa/„teraz” → is living."),
    ],
  },
  {
    id: "present-perfect", group: "present", name: "Present Perfect",
    short: "doświadczenie, wynik teraz, „od jak dawna”",
    when: [
      "<b>Doświadczenie życiowe</b> (kiedy – nieważne): <i>I've been to Japan.</i>",
      "<b>Wynik widoczny teraz</b>: <i>I've lost my keys</i> (i nadal ich nie mam).",
      "<b>Coś, co trwa do teraz</b> (for/since; głównie czasowniki stanu): <i>I've known her for 10 years.</i>",
      "<b>Świeże wiadomości</b>, z <i>just, already, yet</i>: <i>She has just left.</i>",
    ],
    form: [
      ["Twierdzenie", "have/has + <b>III forma</b> (past participle): <b>I have worked / she has gone</b>"],
      ["Przeczenie", "<b>haven't / hasn't</b> + III forma"],
      ["Pytanie", "<b>Have</b> you seen it? · <b>Has</b> he called?"],
    ],
    sig: ["ever", "never", "just", "already", "yet", "so far", "recently", "for", "since", "How long…?"],
    ex: [
      ["I've seen this film three times.", "Widziałem ten film trzy razy."],
      ["She has lived here since 2019.", "Mieszka tu od 2019."],
      ["Have you ever tried sushi?", "Czy kiedykolwiek próbowałeś sushi?"],
      ["They haven't arrived yet.", "Oni jeszcze nie dotarli."],
    ],
    watch: [
      ["I have seen him yesterday.", "I saw him yesterday.", "Z określeniem czasu zakończonego (yesterday, last week, in 2020, ago) → Past Simple."],
      ["I live here since 2019.", "I have lived here since 2019.", "„od 2019” → Present Perfect z since."],
      ["Did you ever be to Spain?", "Have you ever been to Spain?", "ever → Present Perfect."],
    ],
    tip: "Klucz: <b>Present Perfect łączy przeszłość z teraźniejszością</b>. Jeśli mówisz „kiedy” (yesterday, in 2010) – łączenia nie ma → Past Simple. <i>gone</i> = poszedł (i go nie ma), <i>been</i> = był (i wrócił).",
    q: [
      c("I ___ this film three times.", ["saw", "have seen", "see"], 1, "Doświadczenie do tej pory, bez podanego czasu → have seen."),
      c("She ___ in Berlin since 2020.", ["lives", "has lived", "lived"], 1, "since + trwa do teraz → has lived."),
      t("Have you ever ___ (be) to Japan?", ["been"], "III forma od be = been."),
      c("I can't get in. I ___ my keys.", ["have lost", "was losing", "lose"], 0, "Wynik teraz (nie mam kluczy) → have lost."),
      c("They ___ yet.", ["haven't arrived", "didn't arrived", "aren't arrived"], 0, "yet w przeczeniu → Present Perfect: haven't arrived."),
      t("How long ___ you known him?", ["have"], "How long + stan trwający do teraz → have you known."),
      t("I've just ___ (finish) my report.", ["finished"], "just + Present Perfect. III forma od finish = finished."),
      c("___ you ever tried sushi?", ["Did", "Have", "Do"], 1, "ever → Have you ever + III forma."),
    ],
  },
  {
    id: "present-perfect-continuous", group: "present", name: "Present Perfect Continuous",
    short: "trwa od jakiegoś czasu, widać skutki",
    when: [
      "<b>Czynność trwająca do teraz</b>, nacisk na czas: <i>I've been waiting for an hour.</i>",
      "<b>Widoczny skutek niedawnej czynności</b>: <i>You're wet. Have you been running?</i>",
      "<b>Aktualny okres</b>: <i>I've been learning Spanish lately.</i>",
    ],
    form: [
      ["Twierdzenie", "have/has + <b>been</b> + czasownik<b>-ing</b>: <b>I have been working</b>"],
      ["Przeczenie", "<b>haven't / hasn't been</b> working"],
      ["Pytanie", "<b>Have</b> you been working? · How long <b>has</b> she been waiting?"],
    ],
    sig: ["for", "since", "all day", "lately", "recently", "How long…?"],
    ex: [
      ["I've been working since 8 am.", "Pracuję od 8 rano (i nadal)."],
      ["She's been learning English for two years.", "Uczy się angielskiego od dwóch lat."],
      ["It's been raining all day.", "Pada cały dzień."],
      ["Why are you out of breath? Have you been running?", "Czemu się dyszysz? Biegałeś?"],
    ],
    watch: [
      ["I have been knowing him for years.", "I have known him for years.", "Czasowniki stanu (know, like, be, have=posiadać) → zwykły Present Perfect."],
      ["I have been writing three emails.", "I have written three emails.", "Gdy liczysz / podajesz wynik (three emails) → Perfect Simple."],
    ],
    tip: "<b>Continuous = proces i czas trwania</b> („jak długo?”). <b>Simple = wynik i ilość</b> („ile?”, „skończone”).",
    q: [
      c("I'm tired. I ___ all day.", ["have been working", "have worked", "am working"], 0, "Czynność trwała cały dzień i widać skutek (zmęczenie)."),
      c("She ___ English for five years.", ["has been learning", "is learning", "learns"], 0, "for five years + nadal się uczy → has been learning."),
      t("It ___ (rain) all morning; the streets are wet.", ["has been raining"], "Skutek widoczny teraz + czas trwania → has been raining."),
      c("I ___ three emails since breakfast.", ["have written", "have been writing", "am writing"], 0, "Podana liczba (three) → Perfect Simple: have written."),
      c("How long ___?", ["have you waited", "have you been waiting", "are you waiting"], 1, "How long + czynność trwająca → have you been waiting."),
      c("Why are your hands dirty? — I ___ in the garden.", ["have been working", "worked", "work"], 0, "Skutek widoczny teraz → have been working."),
      t("He ___ (not/sleep) well lately.", ["has not been sleeping"], "hasn't been sleeping – lately + proces."),
      c("I ___ my homework. Now I can play.", ["have finished", "have been finishing", "am finishing"], 0, "Zakończony wynik → have finished (finish się rzadko daje w Continuous)."),
    ],
  },

  // ───────────────────────── PAST ─────────────────────────
  {
    id: "past-simple", group: "past", name: "Past Simple",
    short: "zakończone zdarzenia w przeszłości",
    when: [
      "<b>Zakończona czynność</b> w określonym momencie przeszłości: <i>I met her last week.</i>",
      "<b>Kolejne zdarzenia</b> w opowieści: <i>He came in, sat down and started to read.</i>",
      "<b>Dawne stany i nawyki</b>: <i>I lived in Kraków for 5 years</i> (już nie mieszkam).",
    ],
    form: [
      ["Twierdzenie", "czasownik + <b>-ed</b> (regularne) lub <b>II forma</b> (nieregularne): <b>worked, went, saw</b>"],
      ["Przeczenie", "<b>did not (didn't)</b> + czasownik podstawowy: I didn't go"],
      ["Pytanie", "<b>Did</b> you go? – po did zawsze forma podstawowa"],
    ],
    sig: ["yesterday", "last week/year", "in 2019", "two days ago", "when I was young", "What time did…?"],
    ex: [
      ["We went to Rome last year.", "W zeszłym roku pojechaliśmy do Rzymu."],
      ["I didn't see him yesterday.", "Nie widziałem go wczoraj."],
      ["Did you enjoy the party?", "Czy podobała ci się impreza?"],
      ["She opened the door and smiled.", "Otworzyła drzwi i się uśmiechnęła."],
    ],
    watch: [
      ["Did you went there?", "Did you go there?", "Po did czasownik zostaje w formie podstawowej. Przeszłość jest już w did."],
      ["I didn't saw him.", "I didn't see him.", "To samo w przeczeniu."],
      ["When have you bought it?", "When did you buy it?", "Pytanie o czas („kiedy”) → Past Simple."],
    ],
    tip: "Naucz się czasowników nieregularnych <b>parami/trójkami</b>: go–went–gone, see–saw–seen, take–took–taken. Ćwicz je na głos.",
    q: [
      c("We ___ to Rome last year.", ["went", "have gone", "were going"], 0, "last year = zamknięty czas → Past Simple."),
      c("She ___ me yesterday.", ["didn't called", "didn't call", "not called"], 1, "did/didn't + forma podstawowa."),
      t("I ___ (see) him two days ago.", ["saw"], "two days ago → Past Simple; see → saw."),
      c("___ you enjoy the party last night?", ["Did", "Do", "Have"], 0, "Pytanie w Past Simple → Did."),
      c("When ___ you buy that car?", ["have you bought", "did you buy", "do you bought"], 1, "When → Past Simple, forma podstawowa po did."),
      t("He ___ (not/come) to school on Monday.", ["did not come"], "didn't + come (forma podstawowa)."),
      c("Shakespeare ___ Hamlet around 1600.", ["wrote", "has written", "was writing"], 0, "Historyczny fakt → Past Simple."),
      c("I ___ my leg when I was a child.", ["broke", "have broken", "breaks"], 0, "when I was a child = zamknięty czas → broke."),
    ],
  },
  {
    id: "past-continuous", group: "past", name: "Past Continuous",
    short: "coś trwało w przeszłości (tło zdarzeń)",
    when: [
      "<b>Czynność w toku</b> w konkretnym momencie przeszłości: <i>At 8 I was having dinner.</i>",
      "<b>Tło</b> przerwane przez krótkie zdarzenie: <i>I was walking when it started to rain.</i>",
      "<b>Dwie równoległe czynności</b> (<i>while</i>): <i>She was cooking while he was reading.</i>",
    ],
    form: [
      ["Twierdzenie", "<b>was / were</b> + czasownik<b>-ing</b>: I was working, they were working"],
      ["Przeczenie", "<b>wasn't / weren't</b> working"],
      ["Pytanie", "<b>Was</b> she working? · What <b>were</b> you doing?"],
    ],
    sig: ["while", "when", "at 8 pm yesterday", "all evening", "as"],
    ex: [
      ["I was watching TV when the phone rang.", "Oglądałem telewizję, kiedy zadzwonił telefon."],
      ["What were you doing at 9 last night?", "Co robiłeś wczoraj o 21?"],
      ["It was raining, so we stayed home.", "Padało, więc zostaliśmy w domu."],
    ],
    watch: [
      ["I was watching TV when the phone was ringing.", "…when the phone rang.", "Krótkie przerywające zdarzenie → Past Simple, długie tło → Past Continuous."],
      ["I was cooking dinner, then I was washing up.", "I cooked dinner, then I washed up.", "Kolejne zakończone czynności → Past Simple."],
    ],
    tip: "Obrazek: <b>Continuous = film w toku</b> (długa linia), <b>Simple = pstryknięcie</b> (krótkie zdarzenie wpadające w film).",
    q: [
      c("I ___ TV when the phone rang.", ["watched", "was watching", "have watched"], 1, "Trwająca czynność (tło) przerwana przez rang."),
      c("What ___ you doing at 9 last night?", ["were", "did", "have"], 0, "Konkretny moment w przeszłości → were you doing."),
      t("They ___ (play) football when it started to rain.", ["were playing"], "Tło przerwane krótkim zdarzeniem."),
      c("It ___ when I left home, so I took an umbrella.", ["rained", "was raining", "has rained"], 1, "Sytuacja trwała w momencie wyjścia → was raining."),
      c("I ___ dinner, then I washed up.", ["cooked", "was cooking", "have cooked"], 0, "Kolejne zakończone czynności → Past Simple."),
      t("She ___ (not/listen) when the teacher explained.", ["was not listening"], "wasn't listening – czynność w toku (nie słuchała)."),
      c("While I ___ to work, I saw an accident.", ["was walking", "walk", "have walked"], 0, "while + czynność w toku → was walking."),
      t("He broke his arm while he ___ (ski).", ["was skiing"], "while + czynność w toku, przerwana urazem."),
    ],
  },
  {
    id: "past-perfect", group: "past", name: "Past Perfect",
    short: "„wcześniej niż coś w przeszłości”",
    when: [
      "<b>Czynność wcześniejsza</b> niż inna czynność w przeszłości: <i>When I arrived, the film had started.</i>",
      "<b>Wyjaśnienie przyczyny</b>: <i>She was upset because she had lost her wallet.</i>",
      "W mowie zależnej („powiedział, że już…”) i w okresie warunkowym 3.",
    ],
    form: [
      ["Twierdzenie", "<b>had</b> + III forma: I had finished, she had gone"],
      ["Przeczenie", "<b>hadn't</b> + III forma"],
      ["Pytanie", "<b>Had</b> you finished?"],
    ],
    sig: ["before", "after", "by the time", "already", "just", "never … before", "when"],
    ex: [
      ["When I got there, they had left.", "Kiedy dotarłem, już wyszli."],
      ["I had never seen snow before that trip.", "Przed tą podróżą nigdy nie widziałem śniegu."],
      ["She said she hadn't seen him for years.", "Powiedziała, że nie widziała go od lat."],
    ],
    watch: [
      ["After he ate dinner, he had watched TV.", "After he had eaten dinner, he watched TV.", "Perfect dajemy tej czynności, która była <b>wcześniej</b>."],
    ],
    tip: "Past Perfect potrzebuje <b>dwóch punktów</b> w przeszłości. Jeśli jest tylko jedna czynność – zwykle wystarczy Past Simple. Kolejność w opowieści (first…then) często nie wymaga Perfect.",
    q: [
      c("When I arrived, the film ___.", ["started", "had started", "has started"], 1, "Film zaczął się przed moim przyjściem → had started."),
      c("She was upset because she ___ her wallet.", ["lost", "had lost", "was losing"], 1, "Przyczyna wcześniejsza niż stan smutku."),
      t("By the time we got there, they ___ (leave).", ["had left"], "by the time + wcześniejsza czynność → had left."),
      c("I ___ sushi before that trip.", ["had never eaten", "never ate", "have never eaten"], 0, "Doświadczenie przed punktem w przeszłości → had never eaten."),
      c("After he ___ dinner, he watched TV.", ["had eaten", "has eaten", "was eating"], 0, "Wcześniejsza czynność → had eaten."),
      t("She said she ___ (not/see) him for years.", ["had not seen"], "Mowa zależna, wcześniejszy stan → hadn't seen."),
      c("He didn't recognise her; she ___ a lot.", ["had changed", "changed", "has changed"], 0, "Zmiana wcześniejsza niż brak rozpoznania."),
      t("By 6 pm I ___ (finish) all my homework.", ["had finished"], "by + moment w przeszłości → had finished."),
    ],
  },
  {
    id: "past-perfect-continuous", group: "past", name: "Past Perfect Continuous",
    short: "trwało przed innym momentem w przeszłości",
    when: [
      "<b>Czynność trwająca przed innym momentem w przeszłości</b>: <i>I had been waiting for an hour when she came.</i>",
      "<b>Wyjaśnienie stanu w przeszłości</b>: <i>Her eyes were red. She had been crying.</i>",
    ],
    form: [
      ["Twierdzenie", "<b>had been</b> + czasownik-ing: I had been working"],
      ["Przeczenie", "<b>hadn't been</b> working"],
      ["Pytanie", "<b>Had</b> you been working?"],
    ],
    sig: ["for", "since", "all day", "How long…?", "by the time", "before"],
    ex: [
      ["We had been walking for hours when we found the hotel.", "Szliśmy od wielu godzin, gdy znaleźliśmy hotel."],
      ["He was tired because he had been working all night.", "Był zmęczony, bo pracował całą noc."],
    ],
    watch: [
      ["I had been knowing her for years.", "I had known her for years.", "Czasowniki stanu – bez Continuous."],
    ],
    tip: "To „przeszłość Present Perfect Continuous”: przesuń wszystko o jeden krok w przeszłość. Rzadszy czas – najpierw opanuj resztę.",
    q: [
      c("She was exhausted. She ___ for hours.", ["had been running", "has been running", "was run"], 0, "Trwała przed momentem w przeszłości → had been running."),
      c("He ___ for the company for ten years before he quit.", ["had been working", "has been working", "is working"], 0, "Czas trwania przed innym zdarzeniem w przeszłości."),
      t("They ___ (wait) for an hour when the bus finally came.", ["had been waiting"], "for an hour when… → had been waiting."),
      c("Her eyes were red. She ___.", ["had been crying", "was cry", "has cried"], 0, "Wyjaśnienie stanu w przeszłości → had been crying."),
      c("The ground was wet. It ___ all night.", ["had been raining", "has been raining", "rains"], 0, "Przyczyna wcześniejsza + czas trwania."),
      t("I ___ (not/sleep) well, so I felt terrible.", ["had not been sleeping"], "hadn't been sleeping."),
      c("How long ___ before you found a job?", ["had you been looking", "have you been looking", "are you looking"], 0, "found a job = punkt w przeszłości → had you been looking."),
      t("When I met him, he ___ (live) in Spain for a year.", ["had been living"], "for a year before then → had been living."),
    ],
  },

  // ───────────────────────── FUTURE ─────────────────────────
  {
    id: "future-forms", group: "future", name: "Przyszłość: will / going to / Present Continuous",
    short: "3 najważniejsze sposoby mówienia o przyszłości",
    when: [
      "<b>will</b> – decyzja podjęta w chwili mówienia, przewidywanie z opinii, obietnice: <i>I'll help you. I think it will rain.</i>",
      "<b>be going to</b> – wcześniej zaplanowany zamiar lub przewidywanie z dowodów: <i>I'm going to study medicine. Look at those clouds – it's going to rain.</i>",
      "<b>Present Continuous</b> – ustalony plan (termin, miejsce, ktoś się umówił): <i>I'm seeing the dentist at 5.</i>",
      "<b>Present Simple</b> – rozkłady jazdy i harmonogramy: <i>The train leaves at 9.</i>",
      "<b>Zdania czasowe/warunkowe</b> (if, when, as soon as, before, after, until) – po nich <u>nie ma will</u>: <i>I'll call you when I arrive.</i>",
    ],
    form: [
      ["will", "<b>will</b> (’ll) / <b>won't</b> + czasownik podstawowy: I'll go, she won't come"],
      ["going to", "<b>am/is/are going to</b> + czasownik podstawowy"],
      ["Plan", "<b>am/is/are</b> + czasownik-ing + wyraz czasu"],
    ],
    sig: ["tomorrow", "next week", "soon", "I think", "probably", "tonight", "in 2030"],
    ex: [
      ["A: I'm cold. B: I'll close the window.", "A: Zimno mi. B: Zamknę okno."],
      ["Look at the sky! It's going to rain.", "Spójrz na niebo! Będzie padać."],
      ["We're meeting Ola at 7.", "Spotykamy się z Olą o 7."],
      ["I'll call you as soon as I arrive.", "Zadzwonię, jak tylko dotrę."],
    ],
    watch: [
      ["If it will rain, we will stay home.", "If it rains, we will stay home.", "Po if/when/as soon as… – Present Simple, nawet dla przyszłości."],
      ["I'll meet Anna at 5 (już się umówiliśmy).", "I'm meeting Anna at 5.", "Ustalony plan brzmi naturalniej w Present Continuous."],
    ],
    tip: "Szybka zasada: <b>decyzja teraz → will</b>, <b>plan/dowód → going to</b>, <b>umówione → Present Continuous</b>.",
    q: [
      c("A: I'm cold. B: I ___ close the window.", ["will", "am going to", "am closing"], 0, "Spontaniczna decyzja → will."),
      c("Look at those clouds! It ___ rain.", ["will", "is going to", "is"], 1, "Przewidywanie na podstawie dowodów → is going to."),
      c("I ___ my dentist tomorrow at 5; I've booked it.", ["will see", "am seeing", "see"], 1, "Umówiona wizyta → Present Continuous."),
      c("I think Poland ___ win the match.", ["will", "is winning", "wins"], 0, "I think + opinia → will."),
      t("If it rains, we ___ (stay) at home.", ["will stay"], "Okres warunkowy 1: if + Present Simple, will + czasownik."),
      t("I'll call you as soon as I ___ (arrive).", ["arrive"], "Po as soon as – Present Simple, nie will."),
      c("She ___ have a baby in June — she told us yesterday.", ["is going to", "will", "has"], 0, "Wcześniejszy plan/wiadomość → is going to."),
      c("The exam ___ at 9 am on Friday.", ["starts", "will starts", "is going start"], 0, "Rozkład/harmonogram → Present Simple."),
    ],
  },
  {
    id: "future-continuous", group: "future", name: "Future Continuous",
    short: "„o tej porze będę właśnie robić…”",
    when: [
      "<b>Czynność w toku w konkretnym momencie w przyszłości</b>: <i>This time tomorrow I'll be flying to Rome.</i>",
      "<b>Uprzejme pytanie o plany</b>: <i>Will you be using the car tonight?</i>",
      "<b>Coś, co i tak się wydarzy</b> (niezależnie od nas): <i>I'll be passing the shop, so I can buy milk.</i>",
    ],
    form: [
      ["Twierdzenie", "<b>will be</b> + czasownik-ing: I will be working"],
      ["Przeczenie", "<b>won't be</b> working"],
      ["Pytanie", "<b>Will</b> you <b>be</b> working?"],
    ],
    sig: ["this time tomorrow", "at 8 pm tomorrow", "next week at this time", "in July"],
    ex: [
      ["At 10 pm tomorrow I'll be sleeping.", "Jutro o 22 będę spać."],
      ["Will you be using your laptop tonight?", "Będziesz dziś używać laptopa?"],
    ],
    watch: [["I will sleeping.", "I will be sleeping.", "Po will jest be + -ing, nie sam -ing."]],
    tip: "Wyobraź sobie zdjęcie z przyszłości: w tym momencie coś <i>trwa</i>.",
    q: [
      c("This time tomorrow I ___ on a beach.", ["will lie", "will be lying", "lie"], 1, "Czynność w toku o określonej porze → will be lying."),
      c("Don't call at 8. I ___ dinner.", ["will have", "will be having", "am have"], 1, "W tym momencie będzie trwać → will be having."),
      t("At 10 pm tomorrow, she ___ (sleep).", ["will be sleeping"], "Konkretny moment w przyszłości."),
      c("___ you be using the car tonight? Can I borrow it?", ["Will", "Are", "Do"], 0, "Uprzejme pytanie o plany → Will you be using…?"),
      c("In July, we ___ in Greece.", ["will be travelling", "are travel", "will travelled"], 0, "Czynność w toku w przyszłości."),
      t("I ___ (wait) for you at the station at 6.", ["will be waiting"], "W tym momencie już będę czekać → will be waiting."),
      c("Next week at this time he ___ his exam.", ["will be taking", "takes", "has taken"], 0, "at this time next week → will be taking."),
      t("Mum ___ (cook) when you arrive.", ["will be cooking"], "Trwa w momencie Twojego przyjazdu."),
    ],
  },
  {
    id: "future-perfect", group: "future", name: "Future Perfect",
    short: "„do jakiegoś momentu już będzie zrobione”",
    when: [
      "<b>Czynność zakończona przed pewnym momentem w przyszłości</b>: <i>By Friday I'll have finished.</i>",
      "<b>Czas trwania do przyszłego momentu</b>: <i>In June we'll have been married for 20 years.</i>",
    ],
    form: [
      ["Twierdzenie", "<b>will have</b> + III forma: I will have finished"],
      ["Przeczenie", "<b>won't have</b> finished"],
      ["Pytanie", "<b>Will</b> you <b>have</b> finished?"],
    ],
    sig: ["by Friday", "by the time", "by then", "by 2030", "before", "in two years"],
    ex: [
      ["By 2030 they will have built a new bridge.", "Do 2030 roku zbudują nowy most."],
      ["I'll have finished by noon.", "Do południa skończę."],
    ],
    watch: [["By Friday I will finish.", "By Friday I will have finished.", "by + termin → „do tego czasu już zrobione” → Future Perfect."]],
    tip: "Słowo-klucz: <b>by</b> („do” jakiegoś terminu). Po polsku często wystarcza czas przyszły dokonany, po angielsku potrzebujesz <i>will have + III forma</i>.",
    q: [
      c("By Friday I ___ the report.", ["will finish", "will have finished", "am finishing"], 1, "by + termin → Future Perfect."),
      c("In June, they ___ married for 20 years.", ["will be", "will have been", "are"], 1, "Czas trwania do momentu w przyszłości → will have been."),
      t("By the time you arrive, we ___ (eat).", ["will have eaten"], "by the time → will have + III forma."),
      c("By this time next year, she ___ her studies.", ["will have completed", "will complete", "has completed"], 0, "by this time next year → Future Perfect."),
      c("He ___ by noon.", ["won't have finished", "won't finish", "hasn't finished"], 0, "by noon → Future Perfect w przeczeniu."),
      t("___ you have finished by 5? (Will / Do / Are)", ["will"], "Pytanie: Will you have finished by 5?"),
      c("By the end of this course, you ___ 100 new words.", ["will have learned", "will learn", "would have learned"], 0, "Podsumowanie do momentu → will have learned."),
      t("By 2035 scientists ___ (discover) a cure.", ["will have discovered"], "by + rok w przyszłości → will have discovered."),
    ],
  },

  // ───────────────────────── CONSTRUCTIONS ─────────────────────────
  {
    id: "conditionals", group: "constr", name: "Okresy warunkowe (0, 1, 2, 3)",
    short: "if… – co jest, co będzie, co byłoby, co by było, gdyby",
    when: [
      "<b>0</b> – zawsze prawda: <i>If you heat ice, it melts.</i>",
      "<b>1</b> – realna możliwość w przyszłości: <i>If it rains, we'll stay home.</i>",
      "<b>2</b> – mało prawdopodobne/wyobrażone teraz: <i>If I had a million, I would buy an island.</i>",
      "<b>3</b> – nierealne w przeszłości (żal, spekulacja): <i>If I had studied, I would have passed.</i>",
    ],
    form: [
      ["0", "If + <b>Present Simple</b>, <b>Present Simple</b>"],
      ["1", "If + <b>Present Simple</b>, <b>will</b> + czasownik"],
      ["2", "If + <b>Past Simple</b>, <b>would</b> + czasownik (<i>If I were you…</i>)"],
      ["3", "If + <b>Past Perfect</b>, <b>would have</b> + III forma"],
    ],
    sig: ["if", "unless", "when", "as long as", "wish"],
    ex: [
      ["If you mix red and blue, you get purple.", "Jeśli zmieszasz czerwony i niebieski, dostaniesz fioletowy."],
      ["If I were you, I'd apologise.", "Na twoim miejscu przeprosiłbym."],
      ["If we had left earlier, we wouldn't have missed the train.", "Gdybyśmy wyjechali wcześniej, nie spóźnilibyśmy się na pociąg."],
    ],
    watch: [
      ["If I will see him, I will tell him.", "If I see him, I will tell him.", "Po if nie ma will."],
      ["If I would have money, I would travel.", "If I had money, I would travel.", "Po if nie ma would (w typie 2 i 3)."],
    ],
    tip: "Polskie „gdyby” zawsze oznacza 2 lub 3. Sprawdź: dotyczy <b>teraz/przyszłości</b> (2) czy <b>przeszłości</b> (3).",
    q: [
      c("If you heat ice, it ___.", ["melts", "will melt", "would melt"], 0, "Prawda ogólna → typ 0."),
      c("If it rains tomorrow, we ___ at home.", ["will stay", "would stay", "stay"], 0, "Realna możliwość → will."),
      c("If I ___ a million dollars, I would buy an island.", ["had", "have", "would have"], 0, "Typ 2: if + Past Simple."),
      c("If I ___ you, I would apologise.", ["were", "am", "will be"], 0, "If I were you… (typ 2)."),
      c("If she had studied, she ___ the exam.", ["would have passed", "would pass", "will pass"], 0, "Typ 3: would have + III forma."),
      t("If I ___ (know) his number, I would call him.", ["knew"], "Typ 2: if + Past Simple."),
      c("If we ___ earlier, we wouldn't have missed the train.", ["left", "had left", "would leave"], 1, "Typ 3: if + Past Perfect."),
      t("If he ___ (come) tomorrow, I will tell him.", ["comes"], "Typ 1: if + Present Simple (bez will)."),
    ],
  },
  {
    id: "passive", group: "constr", name: "Strona bierna (Passive)",
    short: "kiedy ważne jest „co zrobiono”, a nie „kto”",
    when: [
      "Gdy <b>nie znamy wykonawcy</b> lub jest mało ważny: <i>My bike was stolen.</i>",
      "W tekstach formalnych i naukowych: <i>The experiment was repeated.</i>",
      "Jeśli chcesz dodać wykonawcę → <b>by</b>: <i>The book was written by Orwell.</i>",
    ],
    form: [
      ["Wzór", "<b>be</b> (w odpowiednim czasie) + <b>III forma</b>"],
      ["Present Simple", "It <b>is made</b> in Poland."],
      ["Past Simple", "It <b>was made</b> in 1990."],
      ["Present Perfect", "It <b>has been made</b>."],
      ["Present Continuous", "It <b>is being made</b> now."],
      ["will", "It <b>will be made</b>."],
    ],
    sig: ["by", "was/were + III forma", "has been / have been"],
    ex: [
      ["English is spoken all over the world.", "Angielski jest używany na całym świecie."],
      ["The window was broken yesterday.", "Okno zostało wczoraj rozbite."],
      ["My car is being repaired.", "Mój samochód jest w naprawie."],
    ],
    watch: [["The house built in 1900.", "The house was built in 1900.", "Nie zapomnij czasownika be."]],
    tip: "Ćwicz: weź zdanie w stronie czynnej (<i>They built the bridge</i>), zamień dopełnienie na podmiot (<i>The bridge</i>) i dodaj <i>be + III forma</i> (<i>was built</i>).",
    q: [
      c("English ___ all over the world.", ["speaks", "is spoken", "is speaking"], 1, "Podmiot nie wykonuje czynności → is spoken."),
      c("The window ___ by a ball yesterday.", ["broke", "was broken", "has broken"], 1, "was + III forma."),
      t("This bridge ___ (build) in 1890.", ["was built"], "Past Simple Passive: was built."),
      c("The report ___ by Friday.", ["will be finished", "will finish", "is finish"], 0, "will be + III forma."),
      t("My car ___ (repair) at the moment.", ["is being repaired"], "Present Continuous Passive: is being repaired."),
      c("The letters ___ already.", ["have been sent", "have sent", "were send"], 0, "Present Perfect Passive: have been sent."),
      c("She ___ a prize by the mayor last week.", ["was given", "gave", "is given"], 0, "Past Simple Passive: was given."),
      t("The house ___ (paint) — it looks new.", ["has been painted"], "Present Perfect Passive: wynik teraz."),
    ],
  },
  {
    id: "reported", group: "constr", name: "Mowa zależna (Reported Speech)",
    short: "„powiedział, że…”, „zapytał, czy…”",
    when: [
      "Gdy przekazujesz czyjeś słowa: <i>She said (that) she was tired.</i>",
      "Zwykle <b>cofamy czas o jeden krok</b> i zmieniamy zaimki/wyrażenia czasu.",
    ],
    form: [
      ["am/is → was", "„I am tired” → He said he <b>was</b> tired."],
      ["will → would", "„I will call” → She said she <b>would</b> call."],
      ["Present Perfect / Past Simple → Past Perfect", "„I have finished” → He said he <b>had finished</b>."],
      ["Pytania", "„Do you like pizza?” → She asked <b>if</b> I <b>liked</b> pizza. (bez do/does, szyk oznajmujący)"],
      ["Polecenia", "„Don't be late!” → She told me <b>not to be</b> late."],
      ["Wyrażenia", "now → then · today → that day · tomorrow → the next day · yesterday → the day before"],
    ],
    sig: ["said (that)", "told + osoba", "asked if/whether", "asked + wh-"],
    ex: [
      ["\"I'm busy,\" he said. → He said he was busy.", "Powiedział, że jest zajęty."],
      ["\"Where do you live?\" → She asked where I lived.", "Zapytała, gdzie mieszkam."],
    ],
    watch: [
      ["He said me that he was busy.", "He told me that he was busy. / He said that he was busy.", "<i>tell</i> + osoba, <i>say</i> bez osoby (lub <i>say to</i>)."],
      ["She asked where did I live.", "She asked where I lived.", "W mowie zależnej nie ma inwersji ani do/does."],
    ],
    tip: "Jeśli sytuacja nadal jest aktualna, czasu nie musisz cofać: <i>He said he lives in Kraków</i> – też poprawne.",
    q: [
      c("He said: \"I am tired.\" → He said he ___ tired.", ["was", "is", "has been"], 0, "am/is → was."),
      c("\"I will call you.\" → She said she ___ call me.", ["would", "will", "can"], 0, "will → would."),
      c("\"I have finished.\" → He said he ___ finished.", ["had", "has", "have"], 0, "Present Perfect → Past Perfect."),
      c("\"Do you like pizza?\" → She asked me ___ I liked pizza.", ["that", "if", "what"], 1, "Pytanie tak/nie → if / whether."),
      t("\"Where do you live?\" → He asked where I ___ (live).", ["lived"], "Cofamy czas i szyk oznajmujący: I lived."),
      c("\"Don't be late!\" → She told me ___ late.", ["not to be", "to not be", "don't be"], 0, "Polecenie przeczące → told + osoba + not to + czasownik."),
      c("\"I visited Paris.\" → She said she ___ Paris.", ["had visited", "will visit", "was visiting"], 0, "Past Simple → Past Perfect."),
      c("He told ___ he was busy.", ["me", "to me", "that me"], 0, "tell + osoba bez to."),
    ],
  },
  {
    id: "modals", group: "constr", name: "Czasowniki modalne",
    short: "must, have to, should, can, could, might…",
    when: [
      "<b>must / have to</b> – obowiązek. <b>mustn't</b> = zakaz; <b>don't have to</b> = nie musisz (ale możesz).",
      "<b>should / ought to</b> – rada: <i>You should rest.</i>",
      "<b>can / could / may</b> – umiejętność, pozwolenie, prośba: <i>Could I open the window?</i>",
      "<b>must / might / can't</b> – wniosek/przypuszczenie: <i>He must be tired. She can't be at home.</i>",
    ],
    form: [
      ["Wzór", "modal + <b>czasownik podstawowy</b> (bez to, bez -s): <i>She can swim.</i>"],
      ["Przeszłość", "<b>could / had to / must have + III forma</b> (przypuszczenie o przeszłości)"],
    ],
    sig: ["must", "should", "might", "have to", "could"],
    ex: [
      ["You must wear a seat belt.", "Musisz zapinać pasy."],
      ["You don't have to come.", "Nie musisz przychodzić."],
      ["You mustn't smoke here.", "Nie wolno tu palić."],
      ["It might rain later.", "Może później padać."],
    ],
    watch: [
      ["She cans swim.", "She can swim.", "Modale nie dostają -s."],
      ["I must to go.", "I must go.", "Po modalu nie ma to."],
      ["You mustn't come (chcę powiedzieć: nie musisz).", "You don't have to come.", "mustn't = zakaz, nie „nie musisz”."],
    ],
    tip: "Polskie „nie musisz” → <b>don't have to</b>; „nie wolno” → <b>mustn't</b>. Największa pułapka!",
    q: [
      c("You ___ wear a seat belt. It's the law.", ["must", "might", "would"], 0, "Obowiązek prawny → must."),
      c("You ___ come if you don't want to.", ["don't have to", "mustn't", "can't"], 0, "Brak obowiązku → don't have to."),
      c("You ___ smoke here. It's forbidden.", ["mustn't", "don't have to", "needn't to"], 0, "Zakaz → mustn't."),
      c("___ I open the window?", ["Could", "Must", "Should to"], 0, "Uprzejma prośba → Could I…?"),
      c("You look tired. You ___ get some rest.", ["should", "must to", "would to"], 0, "Rada → should."),
      c("She ___ be at home; her car is outside.", ["must", "can", "should"], 0, "Pewny wniosek → must be."),
      t("I ___ swim when I was five. (umiałem)", ["could"], "Umiejętność w przeszłości → could."),
      c("It ___ rain later, so take an umbrella.", ["might", "must", "should to"], 0, "Możliwość → might."),
    ],
  },
  {
    id: "used-to", group: "constr", name: "used to / would / be used to",
    short: "dawne nawyki vs przyzwyczajenie",
    when: [
      "<b>used to + czasownik</b> – dawny nawyk lub stan, którego już nie ma: <i>I used to smoke.</i>",
      "<b>would + czasownik</b> – dawne powtarzane czynności (nie stany): <i>We would go to the lake every summer.</i>",
      "<b>be/get used to + -ing</b> – być/przyzwyczaić się: <i>I'm used to getting up early.</i>",
    ],
    form: [
      ["used to", "I <b>used to</b> play · I <b>didn't use to</b> play · <b>Did</b> you <b>use to</b> play?"],
      ["be used to", "I <b>am used to</b> the noise / working nights."],
      ["get used to", "It took me a while to <b>get used to</b> living alone."],
    ],
    sig: ["when I was a child", "in the past", "now I…", "it took me a while"],
    ex: [
      ["I used to play the piano.", "Kiedyś grałem na pianinie."],
      ["Did you use to live in London?", "Czy dawniej mieszkałeś w Londynie?"],
      ["I'm used to getting up early.", "Jestem przyzwyczajony do wczesnego wstawania."],
    ],
    watch: [
      ["I didn't used to like it.", "I didn't use to like it.", "Po did/didn't jest use (bez -d)."],
      ["I'm used to get up early.", "I'm used to getting up early.", "be used to + -ing (rzeczownik/gerund)."],
    ],
    tip: "<b>used to + czasownik</b> = kiedyś tak było, już nie. <b>be used to + -ing</b> = jestem do tego przyzwyczajony.",
    q: [
      c("I ___ play the piano when I was a child.", ["used to", "use to", "was used to"], 0, "Dawny nawyk → used to."),
      c("Did you ___ live in London?", ["used to", "use to", "used"], 1, "Po did → use to."),
      c("I ___ getting up early.", ["used to", "am used to", "would"], 1, "Przyzwyczajony do (+ -ing) → am used to."),
      c("When I was young, we ___ go to the lake every summer.", ["would", "are used to", "did"], 0, "Dawne powtarzane czynności → would."),
      c("I ___ have a car, but now I don't.", ["would", "used to", "am used to"], 1, "Dawny stan (have) → used to, nie would."),
      t("She didn't ___ (use) to like coffee.", ["use"], "didn't + use to."),
      c("It took me a while to get ___ the noise.", ["used to", "use to", "using to"], 0, "get used to + rzeczownik/-ing."),
      c("He ___ be shy, but now he's very confident.", ["used to", "is used to", "would"], 0, "Dawny stan → used to."),
    ],
  },
  {
    id: "gerund-infinitive", group: "constr", name: "Gerund (-ing) czy infinitive (to)?",
    short: "enjoy doing, want to do, stop doing/to do…",
    when: [
      "<b>+ -ing</b>: enjoy, avoid, finish, suggest, mind, keep, consider, practise, look forward to <i>(to jest przyimek!)</i>, be interested in.",
      "<b>+ to + czasownik</b>: want, decide, hope, plan, need, agree, promise, manage, learn, refuse, afford.",
      "<b>bez to</b> po modalach (can, must, should…) i <i>make/let</i> + osoba.",
      "<b>Zmiana znaczenia</b>: <i>stop doing</i> (przestać) vs <i>stop to do</i> (zatrzymać się, żeby); <i>remember/forget to do</i> (zrobić, o czym trzeba pamiętać) vs <i>remember doing</i> (pamiętać, że się zrobiło).",
    ],
    form: [
      ["Wzór", "czasownik1 + <b>-ing</b> LUB <b>to + czasownik2</b> – zależy od czasownika1"],
    ],
    sig: ["enjoy + -ing", "want + to", "look forward to + -ing", "can + bez to"],
    ex: [
      ["I enjoy listening to music.", "Lubię słuchać muzyki."],
      ["She decided to change jobs.", "Postanowiła zmienić pracę."],
      ["I'm looking forward to seeing you.", "Nie mogę się doczekać, żeby cię zobaczyć."],
    ],
    watch: [
      ["I enjoy to swim.", "I enjoy swimming.", "enjoy wymaga -ing."],
      ["I look forward to see you.", "I look forward to seeing you.", "W „look forward to” słowo „to” jest przyimkiem → dalej -ing."],
    ],
    tip: "Uczysz się czasownika? Zapamiętaj go razem z formą: <i>enjoy doing</i>, <i>want to do</i>. Nie próbuj zgadywać.",
    q: [
      c("I enjoy ___ to music.", ["listening", "to listen", "listen"], 0, "enjoy + -ing."),
      c("She decided ___ a new job.", ["to find", "finding", "find"], 0, "decide + to."),
      c("He suggested ___ to the cinema.", ["going", "to go", "go"], 0, "suggest + -ing."),
      c("I want ___ you tomorrow.", ["to see", "seeing", "see"], 0, "want + to."),
      t("She avoided ___ (talk) to him.", ["talking"], "avoid + -ing."),
      c("I forgot ___ the door — it was open all night.", ["to lock", "locking", "lock"], 0, "forgot to do = nie zrobiłem, co miałem zrobić."),
      c("I'm looking forward to ___ you.", ["see", "seeing", "seen"], 1, "look forward to + -ing."),
      c("She can ___ well.", ["to swim", "swim", "swimming"], 1, "Po modalu (can) czasownik podstawowy."),
    ],
  },
  {
    id: "questions", group: "constr", name: "Pytania i szyk zdania",
    short: "do/does/did, pytania podmiotowe, pytania pośrednie, tag questions",
    when: [
      "<b>Szyk pytania</b>: (wyraz pytający) + <b>operator</b> + podmiot + czasownik: <i>Where does she live?</i>",
      "<b>Pytania o podmiot</b> (who/what jest podmiotem) – bez do/did: <i>Who broke the window?</i>",
      "<b>Pytania pośrednie</b> (uprzejme) – szyk oznajmujący: <i>Could you tell me where the station is?</i>",
      "<b>Tag questions</b> – „prawda?”: <i>You're coming, aren't you? She can't swim, can she?</i>",
    ],
    form: [
      ["Operator", "be / have / modal / do-does-did – ustawia się przed podmiotem"],
      ["Tag", "zdanie twierdzące → tag przeczący (<i>is it?</i> ↔ <i>isn't it?</i>), przeczące → twierdzący"],
    ],
    sig: ["Who…?", "What…?", "Where…?", "Could you tell me…", "…, isn't it?"],
    ex: [
      ["Where does he live?", "Gdzie on mieszka?"],
      ["Who called you?", "Kto do ciebie dzwonił?"],
      ["Do you know where the station is?", "Wiesz, gdzie jest dworzec?"],
    ],
    watch: [
      ["Where he lives?", "Where does he live?", "W pytaniu potrzebny jest operator."],
      ["Who did call you?", "Who called you?", "Gdy pytamy o podmiot – zwykły szyk jak w zdaniu oznajmującym."],
      ["Do you know where is the station?", "Do you know where the station is?", "Pytanie pośrednie = szyk oznajmujący."],
    ],
    tip: "Po polsku pytanie robisz intonacją („Mieszka tu?”). Po angielsku zawsze potrzebny jest <b>operator</b>: <i>Does he live here?</i>",
    q: [
      c("Where ___ he live?", ["does", "do", "is"], 0, "he + live (główny czasownik) → does."),
      c("Who ___ the window?", ["broke", "did broke", "did break"], 0, "Pytanie o podmiot – bez did."),
      c("Do you know where ___?", ["is the station", "the station is", "does the station"], 1, "Pytanie pośrednie – szyk oznajmujący."),
      c("You're coming, ___?", ["aren't you", "don't you", "isn't you"], 0, "Tag: are → aren't you."),
      c("She can't swim, ___?", ["can she", "can't she", "does she"], 0, "Zdanie przeczące → tag twierdzący z tym samym operatorem."),
      c("How long ___ you been here?", ["have", "did", "are"], 0, "Present Perfect – have you been."),
      t("___ your sister speak French? (Do / Does)", ["does"], "sister = she → Does."),
      c("Could you tell me what time ___?", ["it is", "is it", "does it be"], 0, "Pytanie pośrednie → szyk oznajmujący."),
    ],
  },

  // ───────────────────────── COMPARE ─────────────────────────
  {
    id: "pp-vs-ps", group: "compare", name: "Present Perfect vs Past Simple",
    short: "najczęstszy problem Polaków",
    when: [
      "<b>Past Simple</b>: czas jest podany lub oczywisty i <u>zamknięty</u> (yesterday, in 2015, last week, ago, when…?).",
      "<b>Present Perfect</b>: czas <u>nie jest podany</u> albo jeszcze trwa (ever, never, just, yet, already, since, for, this week/today).",
    ],
    form: [
      ["Past Simple", "I <b>saw</b> him <b>yesterday</b>."],
      ["Present Perfect", "I <b>have seen</b> him <b>(already / before)</b>."],
      ["Trwa do teraz", "I <b>have lived</b> here <b>for</b> 5 years. (nadal mieszkam)"],
      ["Zakończone", "I <b>lived</b> there <b>for</b> 5 years. (już nie mieszkam)"],
    ],
    sig: ["yesterday / ago / in 2015 → PS", "ever / just / yet / since → PP"],
    ex: [
      ["I lost my phone yesterday.", "Zgubiłem wczoraj telefon."],
      ["I've lost my phone. Can you call it?", "Zgubiłem telefon (nie mam go teraz). Możesz zadzwonić?"],
      ["Have you ever been to Spain? Yes, I went there in 2019.", "Byłeś kiedyś w Hiszpanii? Tak, pojechałem tam w 2019."],
    ],
    watch: [["I have seen him yesterday.", "I saw him yesterday.", "yesterday = zamknięty czas → Past Simple."]],
    tip: "Pytanie kontrolne: <b>Czy mówię „kiedy”?</b> Tak → Past Simple. Nie, ważne jest doświadczenie lub wynik teraz → Present Perfect.",
    q: [
      c("I ___ him yesterday.", ["saw", "have seen", "have been seeing"], 0, "yesterday → Past Simple."),
      c("She ___ in Paris in 2015.", ["lived", "has lived", "is living"], 0, "in 2015 = zamknięty czas → lived."),
      c("She ___ in Paris for five years. (nadal mieszka)", ["lived", "has lived", "was living"], 1, "Nadal trwa → has lived."),
      c("We ___ to the museum last Sunday.", ["went", "have been", "have gone"], 0, "last Sunday → Past Simple."),
      c("___ you ever been to Spain?", ["Did", "Have", "Do"], 1, "ever → Present Perfect."),
      t("When ___ you go to Spain? (did / have)", ["did"], "When → Past Simple → did."),
      c("I ___ my phone on the train yesterday.", ["lost", "have lost", "was losing"], 0, "yesterday → Past Simple."),
      c("Poland ___ a member of the EU since 2004.", ["was", "has been", "is being"], 1, "since 2004 (nadal) → has been."),
    ],
  },
];

// Ściągawka: porównanie 12 czasów (wykorzystywana na stronie „Ściągawka”)
const CHEATSHEET = [
  ["Present Simple", "I work", "nawyk, fakt", "always, usually, every day"],
  ["Present Continuous", "I am working", "teraz, plan", "now, at the moment"],
  ["Present Perfect", "I have worked", "doświadczenie, wynik", "ever, just, yet, since, for"],
  ["Present Perfect Cont.", "I have been working", "trwa do teraz, widać skutek", "for, since, all day, lately"],
  ["Past Simple", "I worked", "zakończone w przeszłości", "yesterday, ago, in 2019"],
  ["Past Continuous", "I was working", "trwało (tło)", "while, when, at 8 last night"],
  ["Past Perfect", "I had worked", "wcześniej niż inna przeszłość", "before, by the time, already"],
  ["Past Perfect Cont.", "I had been working", "trwało przed inną przeszłością", "for, since, before"],
  ["Future (will)", "I will work", "decyzja teraz, opinia", "I think, probably"],
  ["Future (going to)", "I am going to work", "plan, dowód", "tomorrow, next week"],
  ["Future Continuous", "I will be working", "w toku w przyszłości", "this time tomorrow"],
  ["Future Perfect", "I will have worked", "zakończone przed terminem", "by Friday, by then"],
];
